import os

from dotenv import load_dotenv

from config.settings import (
    COLLECTION_NAME as DEFAULT_COLLECTION_NAME,
    DB_NAME as DEFAULT_DB_NAME,
    ELASTICSEARCH_URL as DEFAULT_ELASTICSEARCH_URL,
    FIREWALL_ENABLED as DEFAULT_FIREWALL_ENABLED,
    MONGO_URI as DEFAULT_MONGO_URI,
    RISK_THRESHOLD as DEFAULT_RISK_THRESHOLD,
)


load_dotenv()


MONGO_URI = os.getenv("MONGO_URI", DEFAULT_MONGO_URI)
DB_NAME = os.getenv("DB_NAME", DEFAULT_DB_NAME)
COLLECTION_NAME = os.getenv("COLLECTION_NAME", DEFAULT_COLLECTION_NAME)

VIRUSTOTAL_API_KEY = os.getenv("VIRUSTOTAL_API_KEY")
ALIENVAULT_API_KEY = os.getenv("ALIENVAULT_API_KEY")
ABUSEIPDB_API_KEY = os.getenv("ABUSEIPDB_API_KEY")

DEFAULT_FEED_INDICATORS = [
    item.strip()
    for item in os.getenv(
        "DEFAULT_FEED_INDICATORS",
        "203.0.113.10,198.51.100.20,192.0.2.20",
    ).split(",")
    if item.strip()
]

ENABLE_DEMO_FALLBACK = os.getenv("ENABLE_DEMO_FALLBACK", "1") == "1"

RISK_THRESHOLD = int(os.getenv("RISK_THRESHOLD", str(DEFAULT_RISK_THRESHOLD)))
BLOCK_THRESHOLD = int(os.getenv("BLOCK_THRESHOLD", str(RISK_THRESHOLD)))
FIREWALL_ENABLED = os.getenv("FIREWALL_ENABLED", str(DEFAULT_FIREWALL_ENABLED)).lower() in ("1", "true", "yes")
ELASTICSEARCH_URL = os.getenv("ELASTICSEARCH_URL", DEFAULT_ELASTICSEARCH_URL)
ES_INDEX_NAME = os.getenv("ES_INDEX_NAME", "threat_intelligence")
BLOCKED_IPS_COLLECTION = os.getenv("BLOCKED_IPS_COLLECTION", "blocked_ips")
SIEM_ENABLED = os.getenv("SIEM_ENABLED", "1") == "1"
